name: Telegram Proxy Loader

on:
  schedule:
    - cron: "0 */4 * * *"   # every 4 hours
  workflow_dispatch:        # manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      THRD_PARS: '128'
      PARS_DP: '5'
      USE_INV_TC: 'n'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        run: |
          python tgproto.py

      - name: Commit & push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add ch.json ch-inv.json proxies.txt

          git diff --cached --quiet && exit 0

          git commit -m "Update proxies [auto]"
          git push
